language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - 'hhvm'

before_script:
    - composer self-update
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: 'hhvm'
