services:
    app.consolidate_used_files.command:
        class: AppBundle\ConsolidateUsedFiles\Command
        arguments: ["@app.consolidate_used_files.task"]
        tags:
            - { name: console.command }

    app.consolidate_used_files.task:
        class: AppBundle\ConsolidateUsedFiles\Task

    app.show_unused_php_files.command:
        class: AppBundle\ShowUnusedPhpFiles\Command
        arguments: ["@app.show_unused_php_files.task"]
        tags:
            - { name: console.command }

    app.show_unused_public_assets.task:
        class: AppBundle\ShowUnusedPublicAssets\Task

    app.show_unused_public_assets.command:
        class: AppBundle\ShowUnusedPublicAssets\Command
        arguments: ["@app.show_unused_public_assets.task"]
        tags:
            - { name: console.command }

    app.show_unused_php_files.task:
        class: AppBundle\ShowUnusedPhpFiles\Task

    app.show_unused_composer_packages.command:
        class: AppBundle\ShowUnusedComposerPackages\Command
        arguments: ["@app.show_unused_composer_packages.task"]
        tags:
            - { name: console.command }

    app.show_unused_composer_packages.task:
        class: AppBundle\ShowUnusedComposerPackages\Task

    app.show_unused_tables.command:
        class: AppBundle\ShowUnusedMySQLTables\Command
        arguments: ["@app.show_unused_tables.task"]
        tags:
            - { name: console.command }

    app.show_unused_tables.task:
        class: AppBundle\ShowUnusedMySQLTables\Task
        arguments: ["@doctrine.dbal.default_connection"]
