# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.show_unused_composer_packages.command:
        class: AppBundle\ShowUnusedComposerPackages\Command
        arguments: ["@app.show_unused_composer_packages.task"]
        tags:
            - { name: console.command }

    app.show_unused_composer_packages.task:
        class: AppBundle\ShowUnusedComposerPackages\Task

    app.show_unused_tables.command:
        class: AppBundle\ShowUnusedMySQLTables\Command
        arguments: ["@app.show_unused_tables.task"]
        tags:
            - { name: console.command }

    app.show_unused_tables.task:
        class: AppBundle\ShowUnusedMySQLTables\Task
        arguments: ["@doctrine.dbal.default_connection"]
